# Config file for automatic testing at travis-ci.org

language: python

env:
    - TOXENV=py27

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get install -qq python-numpy

install: 
    - pip install -r requirements.txt
    - pip install tox

script:
    tox
