# Config file for automatic testing at travis-ci.org

language: python

env:
    - TOXENV=py27

install: 
    - pip install numpy
    - pip install -r requirements.txt
    - pip install tox

script:
    tox
